version: 2
updates:
- package-ecosystem: bundler
  directory: "/app"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/app"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
